# Download base image
FROM ubuntu:20.04

## set working directory
WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

#add commands to run, the below runs python file: app.py

#CMD [ "python". "./app.py"]

#information about custom image

LABEL maintainer="nickhopgood@gmail.com"
LABEL version="0.1"
LABEL description="This is custom docker image for Flask with uwsgi and nginx."

# Disable Prompt During Packages Installation

#ARG DEBIAN_FRONTEND=noninteractive

# Updata software repository

#RUN apt update

# Install python

#RUN apt install -y python3.8 python.38-dev python3-distutils uwsgi uwsgi-src uuid-dev libcap-dev libpcre3-dev python3-pip && \
#  rm -rf /var/lib/apt/lists* && \
#   apt clean

#RUN apt-get install -y uwsgi-plugin-python3


