on:
  push:
    branches:
      - main
# Build Digital Ocean
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     port: ${{ secrets.PORT }}
    #     script: ls -l
    - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run SSH Command
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'ls -l'
